backend:
  name: gitea
  branch: master
  repo: adroitwhiz/community-doc
  api_root: https://rbcnext.adroit.dev/git/api/v1
  auth_type: pkce
  auth_endpoint: "login/oauth/authorize"
  auth_token_endpoint: "login/oauth/access_token"
  base_url: https://rbcnext.adroit.dev/git
  app_id: 7ccd43a4-e953-4aca-9a3a-57d28a38d439

publish_mode: editorial_workflow
media_folder: static/media
public_folder: /media
collections:
  - name: posts
    label: Posts
    label_singular: 'Post'
    folder: content/posts
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: Template
        name: template
        widget: hidden
        default: post
      - label: Title
        name: title
        widget: string
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: text
      - label: Category
        name: category
        widget: string
      - label: Body
        name: body
        widget: markdown
      - label: Tags
        name: tags
        widget: list
  - name: pages
    label: Pages
    label_singular: 'Page'
    folder: content/pages
    create: true
    slug: '{{slug}}'
    fields:
      - label: Template
        name: template
        widget: hidden
        default: page
      - label: Title
        name: title
        widget: string
      - label: Draft
        name: draft
        widget: boolean
        default: true
      - label: Body
        name: body
        widget: markdown
